spring.application.name=demo
# Cloud Database Connection String
spring.datasource.url=jdbc:mysql://mysql-13a9c18a-ravindusandhakith19-10e0.g.aivencloud.com:19781/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_uth7jK0jTjr8yBgDauk

# Hibernate features for development
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
